services:
  postgres:
    image: postgres:17-alpine
   # user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p0stgr3s}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /root/opt/volumes/POSTGRE:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgre-network
networks:
  postgre-network:
    external: true